@startuml app_context
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v2.4.0
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/users.puml
!include FONTAWESOME/database.puml
!includeurl ICONURL/common.puml
!includeurl ICONURL/devicons2/angularjs.puml
!includeurl ICONURL/devicons2/csharp.puml
!includeurl ICONURL/devicons2/mysql.puml

LAYOUT_WITH_LEGEND()

Person(users, "User", "Authorized Users", $sprite="users")
Container(spa, "SPA", "angular", "The main interface that the customer interacts with", $sprite="angularjs")
Container(api, "API", "c#", "Handles all business logic", $sprite="csharp")
FA5_DATABASE(db1,MySql,database,blue)   


Rel(users,spa,"Uses","[HTTPS]")
Rel(spa,api,"Uses")
Rel_R(api,db1,"Uses")

SHOW_LEGEND(true)
@enduml